src/components/RoomCard.tsx, src/pages/Facility.tsx, src/store/actions.ts, src/store/localStorage.ts, src/store/recordsReducer.ts, src/store/reducer.ts, src/store/types.ts, src/store/web3ModalReducer.ts
=> chore: depbysoft types

src/api/OffersRequest.ts, src/components/MapBox.tsx, src/components/Results.tsx, src/store/types.ts, src/types/offers.ts
Description: 
Fix connection with be
=> fix: connection with win-be, types

src/components/PaymentCard.tsx
Added support for multisig wallets; Added spinned for tx; Changed
approve/permit visual behaviou
=> refactor: 💡 PaymentCard refactored

src/components/PaymentCard.tsx, src/store/localStorage.ts
- removed offers and facilities from localStorage
- lint/prettier fixes
=> fix: remove offers, facilities from local storage

src/components/Results.tsx, src/components/SearchResult.tsx, src/utils/common.ts
SearchResult component slides to right when clicked or selected in
state. Scroll to view when selected
✅ Closes: WIN-22
=> feat: 🎸 add selection effects to searchResult

src/components/Results.tsx
Fix hooks error causing crash
✅ Closes: WIN-22
=> fix: 🐛 hooks error

src/components/MapBox.tsx, src/components/Results.tsx, src/store/actions.ts, src/store/reducer.ts, src/store/selectedFacilityReducer.ts, src/store/types.ts
Show hotel markers on map and include scrolling effects
✅ Closes: WIN-23
=> feat: 🎸 show hotel markers on map

src/Routes.tsx, src/components/Header.tsx, src/components/Search.tsx, src/pages/Home.tsx, src/pages/Search.tsx
Description: 
- init home page 
- fix negative inputs 
- fix search comp
=> feat: home page

src/components/SocialButton.tsx, src/layouts/main/MainFooter.tsx
- Added social media links and reorganized footer links
=> feat: 🎸 social media links

src/components/SocialButton.tsx, src/layouts/main/MainFooter.tsx
Fixed external links to open in different windowns. Added Newsletter
=> feat: 🎸 external links in different windows + Newsletter

src/pages/Checkout.tsx
Not it is possible to select a proper token
=> fix: 🐛 Fixed token selection

src/components/SearchResult.tsx, src/container/facility/FacilityIntroduction.tsx, src/container/facility/FacilityOffers.tsx, src/hooks/useAccommodationsAndOffers.tsx/helpers.ts, src/hooks/useAccommodationsAndOffers.tsx/index.ts
- Offers filtered and added to accommodation object
- new search card design 
- card now redirects on click and shows pin on map onHover
=> feat: new searchCard design

src/container/FaqAccordion.tsx, src/pages/Faq.tsx
- new design for faq
- question and answers data
=> feat: added faq data and new design

package.json, src/api/PricedOffer.ts, src/components/RoomCard.tsx, src/container/facility/FacilityOffers.tsx, src/hooks/useAccommodationsAndOffers.tsx/helpers.ts, yarn.lock
- fixed wrong id in accommodation search
- new offer/price endpoint
=> fix: priceed offer api fix

src/container/FaqAccordion.tsx
Description: 
Current accordion auto close when select different one
=> fix: faq ui, missing answer

src/components/AccountInfo.tsx, src/components/Web3Modal.tsx, src/hooks/useWeb3Modal.ts, src/pages/Bookings.tsx
Popup card with a selected account info
Desktop:
Mobile:
=> feat: 🎸 AccountInfo card component

src/Routes.tsx, src/components/ExternalUnsafeLink.tsx, src/layouts/main/MainFooter.tsx, src/pages/BookingConfirmation.tsx, src/pages/PrivacyPolicy.tsx, src/pages/TermsAndConditions.tsx
Terms and Conditions legal text and small changes on feedback
=> feat: 🎸 Added Terms and Conditions

src/components/RoomCard.tsx, src/containers/facility/FacilityIntroduction.tsx
Begin styling facility introduction
✅ Closes: WIN-166
=> feat: 🎸 initial styling facility introduction

.eslintignore, .prettierignore, src/components/CardMediaFallback.tsx, src/index.tsx, src/utils/hotjar.js
Adding ENV variable check and HotJar ID.
=> chore: add hotjar id

package.json, yarn.lock
This PR updates `@windingtree/win-commons` version that adds configuration for the `Gnosis Chain` as `prod` config.
=> feat: 🎸 Updated common config. Added Gnosis prod config

.github/workflows/ci-prod.yml, package.json, src/config.ts, yarn.lock
This PR add config for Polygon network in production
=> feat: 🎸 Added config  for Polygon in production

src/components/RoomCard.tsx, src/containers/facility/FacilityIntroduction.tsx
- Fixes lowest average room price
- fixes room count and nights on room card
=> Fix hotel details room card

src/components/hook-form/RHFAutocomplete.tsx
=> fix: fix autocomplete

src/components/RoomCard.tsx, src/containers/facility/FacilityGallery.tsx, src/containers/facility/FacilityIntroduction.tsx, src/containers/facility/FacilityOffers.tsx, src/pages/Facility.tsx, src/utils/accommodation.ts
https://user-images.githubusercontent.com/19638455/187676837-cd4883b5-f140-4c0a-8886-49dc1385b78a.mp4
=> feature: hotel details gallery

src/pages/Facility.tsx
=> fix: breadcrumbs route to search page

src/containers/facility/FacilityOffers.tsx
=> fix: 🐛 sort hotel offers by rates

.commitlintrc, .gitignore, .husky/pre-commit, .lintstagedrc, package.json, src/components/AssetSelector.tsx, src/components/NetworkSelector.tsx, src/components/PaymentCard.tsx, src/components/Web3Modal.tsx, src/containers/home/LandingCities.tsx, src/containers/home/LandingConferences.tsx, src/hooks/useWeb3Modal.ts, src/pages/Checkout.tsx, yarn.lock
This PR implements multiple fixes for the payment flow UI
- Changed the style of the `Connect wallet` button on the  Checkout page
- Fixed the Web3Modal bug (unhandled rejection during the connection popup closing). Now infinite connect button progress spinner is fixed
- Added message `Please connect your wallet to proceed with the Payment` to the Checkout page
- Styles of drop-down components for Network and Token selection are changed to the native MUI  behaviour
- Added icons for tokens in the Asset selector
- To every error message has been added a specific suggestion for the user on how to fix the error state
- Added offer expiration checker to the Payment page.
=> Refactor/paymment UI

src/components/AssetSelector.tsx, src/components/MapBox.tsx, src/components/NetworkSelector.tsx, src/components/WinPay.tsx, src/containers/GuestInfoContainer.tsx, src/containers/facility/FacilityIntroduction.tsx, src/hooks/useAccommodationsAndOffers.tsx/index.ts, src/pages/Checkout.tsx, src/pages/Facility.tsx, src/pages/GuestInfo.tsx
This PR implement minor tweaks to the payment UI
=> Refactor/payment UI tweak

src/containers/search/SearchForm.tsx, src/containers/search/SearchScheme.ts, src/containers/search/SelectGuestsAndRooms.tsx
Make the room count input accept numbers from 1 to 9
=> feat: max rooms nine

src/components/MapBox.tsx, src/containers/facility/FacilityOffers.tsx
=> fix: 🐛 date display format

src/containers/home/LandingConferences.tsx
=> feat: 🎸 make event card clickable

src/hooks/useAccommodationsAndOffers.tsx/api.ts, src/hooks/useAccommodationsAndOffers.tsx/helpers.ts, src/pages/Search.tsx
=> feat: 🎸 hide map on invalid location

src/components/MapBox.tsx, src/containers/search/SearchForm.tsx, src/pages/Search.tsx
=> Fix error message wording and NoMap spinner

src/containers/search/SearchForm.tsx
=> fix: 🐛 no accommodation error message

src/components/hook-form/RHFPhoneField.tsx
- Removed the `clear` button from the countries selector
- Fixed the initial state of the countries selector when the user returns from the next page
=> fix: 🐛 Fixed country selector UX

src/components/hook-form/RHFPhoneField.tsx
Replaces previous country code with new in the phone
=> fix: 🐛 Improved country selector UX

src/api/PersonalInfoRequest.ts, src/api/PricedOffer.ts, src/api/index.ts, src/components/RoomCard.tsx, src/containers/GuestInfoContainer.tsx, src/hooks/useAccommodationsAndOffers.tsx/api.ts, src/hooks/useBookings.ts, src/hooks/useBookingsAuth.ts, src/hooks/useRewards.ts
This PR removes `withCredentials` options as default configuration and adds a particular config.
=> fix: 🐛 Removed withCredentials as axios defaults

src/containers/search/SearchForm.tsx, src/containers/search/SearchScheme.ts, src/containers/search/helpers.ts, src/hooks/useAccommodationsAndOffers.tsx/index.ts
- Join validation errors into one statement
- Remove persistent search form error message
=> fix: refactor search form bugs

src/utils/events.ts
=> fix: 🐛 remove 1-day swing

src/containers/home/LandingCities.tsx
=> fix: 🐛 set city card dates into the future

src/containers/search/SearchScheme.ts
=> fix: 🐛 ensure guest count is not less than number of rooms

.github/workflows/ci-prod.yml, .github/workflows/ci-test.yml
Adding new ENV variable `REACT_APP_STL_DEVCON`.
=> feat: add new env variable

.github/workflows/ci-prod.yml
Set `REACT_APP_STL_DEVCON` to `0` for prod build.
=> feat: add new env variable - part 2

src/containers/search/SearchScheme.ts
=> fix: 🐛 prevent zero number of days

.github/workflows/ci-test.yml, src/config.ts, src/containers/search/SearchScheme.ts, src/hooks/useAccommodationsAndOffers.tsx/api.ts, src/utils/logger.ts
Checks in config logic for ENV vars:
```
'REACT_APP_DISABLE_FEATURES'
'REACT_APP_LOG_LEVEL'
```
Also, make sure to use variables from config, rather than directly accessing via `process.env` object.
=> feat: add additional checks for env vars

src/layouts/main/MainHeader.tsx
=> fix: 🐛 tweak group booking header bar font

package.json, src/containers/booking-confirmation/DevconCashbackReward.tsx, yarn.lock
Hey Winding Tree team, 
This PR update token-negotiator version and applies the production token config to be used during Devcon week. 
It also has some fixes for error handling.
The config is remote so we can switch it over to production on our side.
=> Chore: permissionless perks prod config

package.json, src/Routes.tsx, src/components/hook-form/RHFAutocomplete.tsx, src/components/hook-form/RHFPhoneField.tsx, src/components/hook-form/RHFTextField.tsx, src/components/hook-form/index.ts, src/config.ts, src/containers/OrgDetails.tsx, src/containers/booking-confirmation/DevconCashbackReward.tsx, src/containers/facility/GroupBooking/FacilityGroupOffers.tsx, src/containers/facility/GroupBooking/FacilityGroupOffersSummary.tsx, src/pages/OrgInfo.tsx, src/store/actions.ts, src/store/checkOutReducer.ts, src/store/types.ts, src/utils/vat.ts, yarn.lock
This PR adds the Organizer details page.
This page is available via group booking -> offers -> request quote
Or directly via /org-details route
=> feat: 🎸 Org Info page

src/containers/booking-confirmation/DevconCashbackReward.tsx
Just a very small design fix for Devcon cashback. Not a critical issue but it would be nice to add this in.
=> fix: modal button margin

src/layouts/main/MainFooter.tsx
Footer is made mobile friendly now
=> feat: 🎸 Responsive footer

src/containers/home/LandingHero.tsx
=> feat: 🎸 temporary mobile view warning

package.json, src/components/PaymentCard.tsx, src/pages/Checkout.tsx, src/utils/strings.ts, yarn.lock
=> fix: token decimals for payment, checkout pages

src/components/SearchCard.tsx, src/hooks/useAccommodationsAndOffers.tsx/index.ts
=> fix: 🐛 image loading memory bug fix

package.json, src/containers/booking-confirmation/DevconCashbackReward.tsx, yarn.lock
Hey guys,
This PR updates TN library to support multiple keys for same conference ID
=> chore: update TN library to support multiple keys per conference ID

src/components/hook-form/RHFAutocomplete.tsx
=> fix: 🐛 autocomplete bug fix for string arrays

src/components/MapBox.tsx, src/components/Results.tsx, src/components/SearchCard.tsx, src/components/hook-form/RHFAutocomplete.tsx, src/components/hook-form/index.ts, src/containers/search/SearchForm.tsx
- Change selected marker color
- Unselect marker when popup closes
- Show fixed searchCard at bottom of screen in mobile view
- Fix panning to center bug
=> fix: Selected marker color and search card in mobile view

src/containers/search/SearchScheme.ts
=> fix: 🐛 adult count validation error message bug

src/containers/OrgDetails.tsx
=> fix: 🐛 org-details country code validation bug

package.json, src/components/Results.tsx, src/pages/Search.tsx, yarn.lock
Description: 
Fixed search list on mobile 
https://simard.atlassian.net/jira/software/projects/WIN/boards/3?selectedIssue=WIN-745
=> feat: draggable container

src/components/Results.tsx
=> fix: 🐛 broken selected hotel card

src/components/Results.tsx, src/pages/Search.tsx
- search box fixed(sticked) to top 
-  list/map view switch effect fixed
=> fix: mobile list view

src/containers/checkout/CheckoutOverview.tsx/CheckoutIntroduction.tsx, src/utils/strings.ts
Bring the page `checkout details` in line with designs.
=> feat: checkout details

src/containers/checkout/CheckoutOverview.tsx/CheckoutIntroduction.tsx, src/containers/facility/RoomCard.tsx
Include city in Google Maps link.
=> feat: include city in google maps link

package.json, yarn.lock
=> feat: update win-common

src/containers/booking-confirmation/BookingRewards.tsx, src/containers/booking-confirmation/MobileRewardCard.tsx, src/containers/booking-confirmation/RewardCard.tsx
=> feat: responsive booking rewards

src/components/Results.tsx
=> fix: map button size to large

src/containers/checkout/CheckoutOverview.tsx/CheckoutIntroduction.tsx
Adding style fixes and price breakdown for checkout page.
=> feat: style fixes and price breakdown

src/containers/checkout/CheckoutOverview.tsx/CheckoutIntroduction.tsx
=> fix: 🐛 import currencySymbolMap from package

src/components/PreferredCurrencySelector.tsx, src/components/hook-form/RHFArrayCheckbox.tsx, src/containers/search/SearchFilterForm.tsx, src/containers/search/SearchForm.tsx, src/containers/search/SearchPopovers.tsx, src/hooks/useAccommodationsAndOffers/helpers.ts, src/hooks/useAccommodationsAndOffers/index.ts, src/hooks/useAccommodationsAndOffers/useAccommodationsAndOffersHelpers.ts, src/hooks/useAppFilter.ts, src/hooks/usePriceFilter.ts, src/store/actions.ts, src/store/priceFilterReducer.ts, src/store/reducer.ts, src/store/types.ts, src/store/userSettingsReducer.ts, src/utils/accommodation.ts, src/utils/common.ts, src/utils/objects.ts, src/utils/offers.ts, src/utils/price.ts
Filter price form
closes [WIN-405]
[WIN-405]: https://simard.atlassian.net/browse/WIN-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: filter price UI

src/App.tsx, src/components/ErrorBoundary.tsx, src/components/hook-form/RHFAutocomplete.tsx, src/containers/search/SearchForm.tsx, src/containers/search/SearchLocationInput.tsx, src/containers/search/SearchPopovers.tsx, src/hooks/useAppHistory.ts, src/layouts/main/index.tsx
- Show price filter on mobile
- Auto dropdown of location input
- Add Error boundary for uncaught errors
=> feat: mobile view price filter

src/components/hook-form/RHFArrayCheckbox.tsx, src/containers/search/SearchFilterForm.tsx, src/hooks/useCurrencies.ts, src/utils/common.ts, src/utils/price.ts
- Handle currencies for which we have no conversion rate
- Make price filter ranges dynamic using converted rates of preferred currency. Exempt currencies which do not have conversion rate from filter
fixes [WIN-821]
[WIN-821]: https://simard.atlassian.net/browse/WIN-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: customize price filter

src/containers/search/SearchFilterDialog.tsx, src/containers/search/SearchForm.tsx, src/containers/search/SearchPopovers.tsx, src/hooks/useAppHistory.ts
✅ Closes: [WIN-824]
[WIN-824]: https://simard.atlassian.net/browse/WIN-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 search form bug in mobile

package.json, src/components/MapBox.tsx, src/containers/checkout/CheckoutOverview.tsx/CheckoutIntroduction.tsx, src/containers/checkout/CheckoutSummary.tsx, src/containers/facility/FacilityIntroduction/index.tsx, src/containers/facility/FacilityOffers/FacilityOffersMultipleSummary.tsx, src/containers/facility/FacilityOffers/FacilityOffersSelectMultiple.tsx, src/containers/facility/FacilityOffers/offer-item/OfferItemSelectMultiple.tsx, src/containers/facility/FacilityOffers/offer-item/OfferItemSelectOne.tsx, src/containers/search/SearchCard.tsx, src/hooks/useAccommodationsAndOffers/helpers.ts, src/hooks/useAccommodationsAndOffers/index.ts, src/hooks/useAppHistory.ts, src/utils/price.ts, yarn.lock
✅ Closes: [WIN-309] [WIN-410] [WIN-307]
[WIN-309]: https://simard.atlassian.net/browse/WIN-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIN-410]: https://simard.atlassian.net/browse/WIN-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIN-307]: https://simard.atlassian.net/browse/WIN-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 show uniform preferred currency on all pages

package.json, src/components/MessageBox.tsx, src/components/PaymentCard.tsx, src/containers/checkout/WinPay.tsx, yarn.lock
win-commons package release and version update needed!
https://github.com/windingtree/win-commons/pull/18
=> Breaking changes: Feat/on ramp

src/utils/date.ts
✅ Closes: [WIN-829]
[WIN-829]: https://simard.atlassian.net/browse/WIN-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 handle string dates in "daysBetween" function

package.json, src/components/ExternalLink.tsx, src/components/MessageBox.tsx, src/components/PaymentCard.tsx, src/containers/checkout/WinPay.tsx, src/pages/Bookings.tsx, yarn.lock
MUST MERGE win-commons FIRST AND UPDATE PACKAGE VERSION: https://github.com/windingtree/win-commons/pull/20
=> fix: native token on ramp link

src/containers/facility/FacilityIntroduction/index.tsx, src/containers/facility/FacilityOffers/offer-item/OfferItemSelectOne.tsx, src/hooks/useAccommodationsAndOffers/helpers.ts, src/hooks/useAccommodationsAndOffers/index.ts, src/hooks/useAccommodationsAndOffers/useAccommodationsAndOffersHelpers.ts, src/hooks/useCurrencies.ts
Price was too low in case of multiple rooms were searched
✅ Closes: [WIN-132]
[WIN-132]: https://simard.atlassian.net/browse/WIN-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 WIN-132 Getting same price for 1 room and 5 rooms

src/containers/GuestInfoContainer.tsx, src/containers/booking-confirmation/BookingRewards.tsx, src/containers/facility/FacilityOffers/offer-item/OfferItemSelectOne.tsx, src/hooks/useNetworkId.ts, src/pages/Checkout.tsx, src/store/types.ts, yarn.lock
https://simard.atlassian.net/browse/WIN-918
=> fix: wrong priced offer id passed to /guest

src/api/AccommodationsAndOffers.ts, src/components/MapBox.tsx, src/containers/facility/FacilityOffers/FacilityOffersSelectMultiple.tsx, src/containers/facility/FacilityOffers/FacilityOffersSelectOne.tsx, src/containers/facility/FacilityOffers/FacilitySearchFormProvider.tsx, src/containers/facility/FacilityOffers/FacilitySearchInputs.tsx, src/containers/facility/FacilityOffers/index.tsx, src/containers/search/SearchAlert.tsx, src/containers/search/SearchForm.tsx, src/containers/search/SearchScheme.ts, src/containers/search/helpers.ts, src/hooks/useAccommodation.tsx, src/hooks/useAccommodationsAndOffers.ts, src/layouts/main/MainFooter.tsx, src/pages/GuestInfo.tsx, src/pages/OrgInfo.tsx, src/utils/logger.ts, src/utils/useAccommodationsAndOffers.ts
fix: 🐛 fix UI issues
✅ Closes: [WIN-894] [WIN-895] [WIN-896] [WIN-921] [WIN-923]
[WIN-894]: https://simard.atlassian.net/browse/WIN-894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIN-895]: https://simard.atlassian.net/browse/WIN-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIN-896]: https://simard.atlassian.net/browse/WIN-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIN-921]: https://simard.atlassian.net/browse/WIN-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIN-923]: https://simard.atlassian.net/browse/WIN-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> fix: Fix UI issues

src/containers/search/SearchScheme.ts
✅ Closes: [WIN-942]
[WIN-942]: https://simard.atlassian.net/browse/WIN-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 start date in the past bug

package.json, src/hooks/useCurrencies.ts, src/utils/price.ts, yarn.lock
=> fix: upgrade `glider-types` and remove `isAmountBeforeTax` and `decimalPlaces`

src/containers/search/SearchForm.tsx
✅ Closes: [WIN-943]
[WIN-943]: https://simard.atlassian.net/browse/WIN-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 set default values for guest and room counts

src/utils/date.ts
=> fix: rm parsing on label

src/api/AccommodationOffers.ts, src/api/cache.ts, src/components/PreferredCurrencySelector.tsx, src/containers/GuestInfoContainer.tsx, src/containers/facility/FacilityIntroduction/HeaderButton.tsx, src/containers/facility/FacilityIntroduction/index.tsx, src/containers/facility/FacilityOffers/offer-item/OfferItemSelectOne.tsx, src/containers/search/SearchCard.tsx, src/hooks/useAccommodationMultiple.ts, src/hooks/useCurrencies.ts, src/utils/accommodationHookHelper.ts
=> fix: 🐛 amend displayed price calculations
